name: Bops
version: '1.1.5'
main: com.bops.BopsPlugin
api-version: '1.21'
description: Player currency plugin
soft-depend: [PlaceholderAPI]

commands:
  bops:
    description: Manage your Bops balance
    usage: /bops [balance|pay|top|give|take|set|reload] [args...]

permissions:
  bops.admin:
    description: Access to admin Bops commands (give, take, set, reload, check others' balances)
    default: op
